### ISSUE TITLE
Comment:

### ISSUE THREAD

**Issue by deanrad** [stubailo/meteor-reactive-method#1]
Could you show an example if you had to feed the output of one Meteor.call into another ? 

I might be convinced to retire a different package I'm using you could support this.

**Comment by stubailo** [comment]
```
Template.foo.helpers({
    methodResult: function () {
        var result1 = ReactiveMethod.call("myMethod", "a", "b");

        if (result1) {
            return ReactiveMethod.call("myMethod2", result1, "b");
        }
    }
});
```

That should work. Curious, which other package were you using?

**Comment by deanrad** [comment]
Oh, that's interesting! I didn't realize that would work "out-of-the-box", now I'm definitely going to have to see how you did that. 

I made this package as a spike, https://github.com/chicagogrooves/deanius-meteor-promise, but the core team told me [here](https://github.com/meteor/meteor/issues/3776) that your package was more the way they envisioned going (good job!)

**Comment by deanrad** [comment]
Cross-referencing the thread in `meteor/meteor` that led me to your library.
Some discussion comparing Promises as in [meteor-promise](https://github.com/chicagogrooves/deanius-meteor-promise) to Reactivity as implemented here.

https://github.com/meteor/meteor/issues/3776

Its a neat package you've made, but I wonder if you can verify that what I say there is correct, about running a function essentially as many times as you have `ReactiveMethod.call`, because that's how many invalidations are done.
