### ISSUE TITLE
invalidate only works once, removes computation

### ISSUE THREAD

**Issue by ecwyne** [stubailo/meteor-reactive-method#10]
Not certain exactly why this is the case, but once a call is invalidated it removes the computation and is not able to be invalidated again.

Reproduction: https://github.com/ecwyne/reactive-method-issue-10

**Comment by stubailo** [comment]
Thanks, a repro would be much appreciated!

**Comment by ecwyne** [comment]
@stubailo Here's the repro

**Comment by ecwyne** [comment]
Especially notice that you can only click `invalidate` button once.

**Comment by ecwyne** [comment]
Is a `Computation` automatically "stopped" onInvalidate?

https://github.com/meteor/meteor/blob/devel/packages/tracker/tracker.js#L567

And then ReactiveMethod deletes computation [here](https://github.com/stubailo/meteor-reactive-method/blob/master/reactive-method.js#L95)?

**Comment by stubailo** [comment]
I don't think you posted the repro when you said "Here's the repro"

**Comment by ecwyne** [comment]
Look at the original comment. My bad

**Comment by ecwyne** [comment]
I believe I got it working. Check out how I did so manually in the `working` branch of my repo

https://github.com/ecwyne/reactive-method-issue-10/blob/working/invalidate-example.js#L16-L17

**Comment by ecwyne** [comment]
After deleting the `_reactiveMethodData` property we need to run the [`Computation._compute()`](https://github.com/meteor/meteor/blob/devel/packages/tracker/tracker.js#L314) method instead of the [`Computation.invalidate()`](https://github.com/meteor/meteor/blob/devel/packages/tracker/tracker.js#L268) method

**Comment by ecwyne** [comment]
PR: https://github.com/stubailo/meteor-reactive-method/pull/11

**Comment by Dsyko** [comment]
I ran into this issue as well, hoping PR #11 fixes this :)

**Comment by patrickdevivo** [comment]
I'm having this issue as well, has it been resolved by PR #11?

**Comment by bshamblen** [comment]
+1

**Comment by andfs** [comment]
I think that the error is because the command:
`recordMethodComputation(cc, serializedArgs);`

is inside the else and this command should run for both conditions (if and else)

**Comment by saliksaly** [comment]
+1
