### ISSUE TITLE
Don't auto update when the Collection updated.

### ISSUE THREAD

**Issue by thearabbit** [stubailo/meteor-reactive-method#12]
I have

``` js
// --------------Server
Meteor.methods({
   getData: function(){
      var data = Collection.Customer.find().fetch();
      return data;
   }
})

// ----------------Client
// Template
{{#each data}}
...............
{{/each}}

// Helper
data: function(){
   var data = ReativeMethod.calle('getData');
   return data;
}
```

Don't auto update, when I update collection.
Please help me.

**Comment by stubailo** [comment]
@thearabbit if you want to push data from the server to the client, you should use `Meteor.publish` and `Meteor.subscribe`. That's what they are for. This package is only for requesting data, which means later updates are not pushed.

**Comment by thearabbit** [comment]
Thanks, I want to generate reports the related with many collections
So I can't use pu/sub.
Have any way to do???

**Comment by stubailo** [comment]
You can publish several collections at once with a publication. You can also use a custom publication to publish transformed data: http://docs.meteor.com/#/full/meteor_publish

Check out how to use `this.added`/`this.changed`. It's not super easy to use, but it's designed for this particular case.

**Comment by thearabbit** [comment]
Thanks again, I will check it.
