### ISSUE TITLE
[Feature] - Template Helper

### ISSUE THREAD

**Issue by ecwyne** [stubailo/meteor-reactive-method#13]
I've found myself making loads of template helpers that simply return the result of a reactive method. I was thinking of creating a global helper to accomplish this which could easily be added to the package itself.
# Implementation

``` javascript
Template.registerHelper('ReactiveMethodCall', function (methodName){
    return ReactiveMethod.apply(methodName, _.rest(_.toArray(arguments)));
});

Template.registerHelper('ReactiveMethodApply', function (methodName, args){
    return ReactiveMethod.apply(methodName, args);
});
```
# Use

``` html
<template name="mySuperCoolTemplate">
  {{ReactiveMethodCall 'mySuperCoolMethod' 'arg1' 'arg2'}}
</template>
```

**Comment by deanrad** [comment]
You might want to check out this as well, for different semantics: https://github.com/okgrow/meteor-promise. But, yes, using a helper like you've done is a cool idea!
