### ISSUE TITLE
Not working with ReactJS

### ISSUE THREAD

**Issue by JWo1F** [stubailo/meteor-reactive-method#17]
Thanks for this package, but the one don't working with ReactJS (ReactMeteorData mixin).
For example:

``` javascript
React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData() {
    return {
      count: ReactiveMethod.call('count')
    };
  },
  render() {
    return <div>{this.data.count}</div>;
  }
});
```

When we will try use this we will have an infinity loop. Fix it, please!

**Comment by shirk3y** [comment]
Same issue here. I also use `react-meteor-data`

**Comment by stubailo** [comment]
I'm probably not going to fix this, but if you identify the problem and need help with a PR, I can help.

**Comment by SevenZark** [comment]
I'm having the same problem. It's a shame the Owner doesn't care. I can't just re-architect my entire project to not use React, so the only choice I have is to not use this library, which looks really helpful.
