### ISSUE TITLE
Could i use reative method in iron-router?

### ISSUE THREAD

**Issue by thearabbit** [stubailo/meteor-reactive-method#5]
I have like this

``` javascript
   // In router
    this.render('myTemplate', {
        data: function () {
            return ReactiveMethod.call("myMethod", "a", "b");;
    });
```

**Comment by stubailo** [comment]
I think it should work - have you tried it?

**Comment by thearabbit** [comment]
Not work for me.

**Comment by stubailo** [comment]
Interesting - could you give me an app where you have this implemented that I could take a look at?

**Comment by stubailo** [comment]
Closing due to lack of reproduction.

**Comment by rabbittc** [comment]
Sorry, I am late.

**Comment by stubailo** [comment]
Do you have a reproduction of it not working with iron router?

**Comment by rabbittc** [comment]
Now it work fine.
Thanks again :100:
