### ISSUE TITLE
[feature] - trigger method to rerun

### ISSUE THREAD

**Issue by ecwyne** [stubailo/meteor-reactive-method#6]
It would be useful to trigger ReactiveMethod to invalidate previously returned results and rerun.
### Proposed API

``` javascript
Template.myTemplate.helpers({
  helperName: function (){
    return ReactiveMethod.call('methodName', 'a', 'b');
  }
})

//elsewhere
ReactiveMethod.invalidate('methodName', 'a', 'b');
//helperName reruns method and returns new result
```
### Implementation

reactive-method.js

``` javascript
  ReactiveMethod = {
    call: ...
    apply: ...
    invalidate: function (/* arguments */){
      var cc = Tracker.currentComputation;
      //ensure computation existence, serialize args, etc...
      delete cc._reactiveMethodData[serializedArgs];
      cc.invalidate();
    }
  }
```

I am more than willing to implement this and create a PR. I believe this method could be called "invalidate" or "changed" or "rerun", did't know if you'd have any preferences or any other thoughts on implementing this API @stubailo

**Comment by stubailo** [comment]
I'd love to accept a PR for this, but unfortunately it's not as simple as your proposed implementation because `Tracker.currentComputation` will not be the correct object. It might require changing the result caching to be global instead of per-computation.

**Comment by ecwyne** [comment]
@stubailo 

Here's a working implementation. I would love to hear your thoughts
https://github.com/stubailo/meteor-reactive-method/compare/master...ecwyne:master

**Comment by stubailo** [comment]
Wow, looks nice!

**Comment by stubailo** [comment]
Going to review now.

**Comment by stubailo** [comment]
Done! Published 1.0.2 with this feature. I decided to split up `invalidateCall` and `invalidateApply`, seemed cleaner than supporting two APIs in one.

**Comment by ecwyne** [comment]
Great! Glad to have this feature! Glad you were able to figure out a way to not [store computations forever](https://github.com/stubailo/meteor-reactive-method/blob/master/reactive-method.js#L96-L97)!

**Comment by stubailo** [comment]
Haha yeah with these kinds of libraries it's easy to accidentally introduce memory leaks..
